/* DO NOT EDIT THIS FILE */

#include <ctype.h>
#include <memory>
#include <new>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define STBI_ONLY_PNG
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

#include "image.h"
#include "log.h"

/* Guards the live "processed X/Y" progress line below: pthread/tbb pipelines
 * can call image_dir_save() from several worker threads at once. */
static pthread_mutex_t progress_mutex = PTHREAD_MUTEX_INITIALIZER;

/* Matches the names produced by image_dir_load_next() (e.g. "0000.png"), so
 * pipeline outputs like "serial-0000.png" aren't counted as source images. */
static bool is_source_image_name(const char* name) {
    size_t len = strlen(name);
    if (len < 5 || strcmp(name + len - 4, ".png") != 0) {
        return false;
    }

    for (size_t i = 0; i < len - 4; i++) {
        if (!isdigit((unsigned char)name[i])) {
            return false;
        }
    }

    return true;
}

static size_t count_source_images(const char* dir_name) {
    DIR* dir = opendir(dir_name);
    if (dir == NULL) {
        return 0;
    }

    size_t count;
    struct dirent* entry;

    for (count = 0; (entry = readdir(dir)) != NULL;) {
        if (is_source_image_name(entry->d_name)) {
            count++;
        }
    }

    closedir(dir);
    return count;
}

image_t* image_create(size_t id, size_t width, size_t height) {
    image_t* image = new (std::nothrow) image_t{};
    if (image == NULL) {
        LOG_ERROR("new image_t failed");
        goto fail_exit;
    }

    image->id     = id;
    image->width  = width;
    image->height = height;

    try {
        image->pixels.resize(image->width * image->height);
    } catch (const std::bad_alloc&) {
        LOG_ERROR("pixels.resize failed");
        goto fail_free_image;
    }

    return image;

fail_free_image:
    delete image;
fail_exit:
    return NULL;
}

image_t* image_create_from_png(char* filename) {
    if (filename == NULL) {
        LOG_ERROR_NULL_PTR();
        return NULL;
    }

    int width;
    int height;
    int channels;

    /* forces 8 bit depth, RGBA format regardless of the source PNG's color type */
    std::unique_ptr<unsigned char, decltype(&stbi_image_free)> data(
        stbi_load(filename, &width, &height, &channels, 4), &stbi_image_free);
    if (!data) {
        LOG_ERROR("stbi_load failed for `%s`: %s", filename, stbi_failure_reason());
        return NULL;
    }

    image_t* image = image_create(0, width, height);
    if (image == NULL) {
        return NULL;
    }

    memcpy(image->pixels.data(), data.get(), static_cast<size_t>(width) * height * 4);
    return image;
}

image_t* image_copy(image_t* image) {
    image_t* new_image = image_create(image->id, image->width, image->height);
    if (new_image == NULL) {
        goto fail_exit;
    }

    for (int j = 0; j < image->height; j++) {
        for (int i = 0; i < image->width; i++) {
            pixel_t* pixel     = image_get_pixel(image, i, j);
            pixel_t* new_pixel = image_get_pixel(new_image, i, j);

            *new_pixel = *pixel;
        }
    }

    return new_image;

fail_exit:
    return NULL;
}

void image_destroy(image_t* image) {
    delete image;
}

int image_save_png(image_t* image, char* filename) {
    if (image == NULL || filename == NULL) {
        LOG_ERROR_NULL_PTR();
        return -1;
    }

    /* output is 8 bit depth, RGBA format */
    int stride = static_cast<int>(image->width) * 4;
    if (!stbi_write_png(filename, static_cast<int>(image->width), static_cast<int>(image->height), 4,
                         image->pixels.data(), stride)) {
        LOG_ERROR("stbi_write_png failed for `%s`", filename);
        return -1;
    }

    return 0;
}

image_t* image_dir_load_next(image_dir_t* image_dir) {
    const size_t buffer_size = 256;
    char buffer[buffer_size];
    int count;
    image_t* image;

    if (image_dir->stop) {
        goto stop_exit;
    }

    count = snprintf(buffer, buffer_size, "%s/%04ld.png", image_dir->input_dir_name, image_dir->load_current);
    if (count >= buffer_size - 1) {
        LOG_ERROR("buffer too small");
        goto fail_exit;
    }

    if (access(buffer, F_OK) < 0) {
        if (image_dir->load_current == 0) {
            LOG_ERROR("no image found in directory `%s`", image_dir->input_dir_name);
        }
        goto fail_exit;
    }

    image = image_create_from_png(buffer);
    if (image == NULL) {
        goto fail_exit;
    }

    image->id = image_dir->load_current++;
    return image;

stop_exit:
fail_exit:
    return NULL;
}

int image_dir_save(image_dir_t* image_dir, image_t* image) {
    const size_t buffer_size = 256;
    char buffer[buffer_size];
    int count;
    size_t completed;
    size_t total;

    count =
        snprintf(buffer, buffer_size, "%s/%s-%04ld.png", image_dir->output_dir_name, image_dir->save_prefix, image->id);
    if (count >= buffer_size - 1) {
        LOG_ERROR("buffer too small");
        goto fail_exit;
    }

    if (image_save_png(image, buffer) < 0) {
        goto fail_exit;
    }

    pthread_mutex_lock(&progress_mutex);
    completed = ++image_dir->completed;
    total     = image_dir->total;
    printf("\rProcessing images: %zu/%zu", completed, total);
    if (completed >= total) {
        printf("\n");
    }
    fflush(stdout);
    pthread_mutex_unlock(&progress_mutex);

    return 0;

fail_exit:
    return -1;
}

void image_dir_reset(image_dir_t* image_dir, const char* input_dir_name, const char* output_dir_name,
                     const char* save_prefix) {
    image_dir->input_dir_name  = input_dir_name;
    image_dir->output_dir_name = output_dir_name;
    image_dir->save_prefix     = save_prefix;
    image_dir->load_current    = 0;
    image_dir->total           = count_source_images(input_dir_name);
    image_dir->completed       = 0;
}
